// models/user.model.ts

export type UserRole =
  | 'SUPER_ADMIN'
  | 'ADMIN'
  | 'STAFF'
  | 'CUSTOMER';

export interface User {
  user_id: string; 
  // PRIMARY KEY
  // UUID generated by database (gen_random_uuid)

  brand_id: string | null;
  // FOREIGN KEY → brands.brand_id
  // Nullable (for SUPER_ADMIN)

  branch_id: string | null;
  // FOREIGN KEY → branches.branch_id
  // Nullable (for brand-level users)

  username: string;
  // Required
  // Display / login name

  email: string;
  // Required
  // UNIQUE
  // Used for authentication

  password_hash: string;
  // Required
  // Hashed password (NEVER store plain password)

  full_name: string | null;
  // Optional
  // User's full name

  phone: string | null;
  // Optional
  // Contact number

  role: UserRole | null;
  // Enum constraint:
  // SUPER_ADMIN | ADMIN | STAFF | CUSTOMER

  status: string;
  // Default: 'active'
  // Can be used for soft-deactivation

  profile_photo: string | null;
  // Optional
  // URL to profile image

  created_at: string;
  // Timestamp
  // Automatically set by DB

  updated_at: string;
  // Timestamp
  // Automatically updated
}
